[package]
name = "i3-toggle-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.36.0"
tokio-i3ipc = "0.16.0"
tokio-stream = "0.1.14"
